substitutions:
  name: sticks3
  friendly_name: StickS3

esphome:
  name: ${name}
  friendly_name: ${friendly_name}

esp32:
  variant: esp32s3
  flash_size: 8MB
  framework:
    type: esp-idf

wifi:
  ssid: "SC"
  password: "8447Ce8086"
  manual_ip:
    static_ip: 192.168.1.222
    gateway: 192.168.1.1
    subnet: 255.255.255.0
  ap:

api:
  encryption:
    key: "4yIspKQlOBu34SLnIQOFeNAQpk3Ke6kX18FTekvpaQk="

ota:
  - platform: esphome

logger:
  level: VERBOSE
  baud_rate: 0

i2c:
  - id: bsp_i2c
    sda: GPIO47
    scl: GPIO48
    scan: true
    frequency: 100kHz

i2s_audio:
  i2s_lrclk_pin: GPIO15
  i2s_bclk_pin: GPIO17
  i2s_mclk_pin: GPIO18

# ES8311 audio codec init
audio_dac:
  - platform: es8311
    id: es8311_dac
    bits_per_sample: 16bit
    sample_rate: 48000
    use_microphone: true
    mic_gain: 42DB
    use_mclk: false
    i2c_id: bsp_i2c

microphone:
  - platform: i2s_audio
    id: mic_a
    adc_type: external
    i2s_din_pin: GPIO16
    sample_rate: 16000
    bits_per_sample: 16bit
    channel: right

speaker:
  - platform: i2s_audio
    id: speaker_a
    dac_type: external
    i2s_dout_pin: GPIO14
    sample_rate: 16000
    bits_per_sample: 16bit
    audio_dac: es8311_dac

media_player:
  - platform: speaker
    name: "StickS3 Speaker"
    id: sticks3_speaker
    announcement_pipeline:
      speaker: speaker_a
      format: WAV
      sample_rate: 24000
      num_channels: 1

voice_assistant:
  microphone: mic_a
  media_player: sticks3_speaker
  use_wake_word: false

binary_sensor:
  - platform: gpio
    name: "Button KEY1"
    pin:
      number: GPIO11
      mode: INPUT_PULLUP
      inverted: true
    on_press:
      - voice_assistant.start

  - platform: gpio
    name: "Button KEY2"
    pin:
      number: GPIO12
      mode: INPUT_PULLUP
      inverted: true
    on_press:
      - voice_assistant.stop
