substitutions:
  name: stackchan
  friendly_name: StackChan

packages:
  stackchan.bsp:
    url: https://github.com/m5stack/esphome-yaml
    files: [examples/kit/stackchan-bsp.factory.yaml]
    ref: main
    refresh: 0s

wifi:
  ssid: "SC"
  password: "8447Ce8086"
  manual_ip:
    static_ip: 192.168.1.180
    gateway: 192.168.1.1
    subnet: 255.255.255.0

api:
  encryption:
    key: "4yIspKQlOBu34SLnIQOFeNAQpk3Ke6kX18FTekvpaQk="

ota:
  - platform: esphome
